export const SUPERHEROES = [
  'Spider-Man',
  'Batman',
  'Wonder Woman',
  'Iron Man',
  'Captain America',
  'Thor',
  'Hulk',
  'Black Widow',
  'Superman',
  'Aquaman',
  'The Flash',
  'Captain Marvel',
  'Doctor Strange',
  'Black Panther',
  'Scarlet Witch',
  'Wolverine',
  'Deadpool',
  'Green Lantern',
  'Shazam',
  'Ant-Man',
  'Supergirl',
  'Green Arrow'
];
